package com.example.demo.mapper;

import com.example.demo.entity.TbParkingSpace;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TbParkingSpaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_parking_space
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    int insert(TbParkingSpace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_parking_space
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    int insertSelective(TbParkingSpace record);
}